#!/usr/bin/env bash
# shellcheck disabled=2154
# Configure HAProxy load balancer server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 487275-web-01 100.25.188.244
        server 487275-web-02 34.299.55.60" >> /etc/haproxy/haproxy.cfg

service haproxy restart
