#!/usr/bin/env bash
# Displays information about the file `school`.

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file does not exit"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school file is not empty"
  fi
else
  echo "school is a regular file"
fi
